#ifndef __PRIMITIVES_H__
#define __PRIMITIVES_H__

#include "MathGeoLib/include/Geometry/Sphere.h"
#include "MathGeoLib/include/Geometry/Capsule.h"

#include "R_Sphere.h"

class R_Primitive
{
public:
	R_Primitive(){}
};


class R_Capsule
{
public:
	R_Capsule(LineSegment, float);

	bool Intersects(R_Sphere);
	Capsule* capsule;

};

/*HAD TO SPLIT SPHERE INTO ITS OWN FILE CAUSE OF LACK OF COHERENCE.
THIS IS TEMPORARY AS SPHERE, CAPSULE ETC.. HAVE THEIR OWN CLASSES.
NOT SURE IF A WRAP IS NEEDED. WE DECIDE THAT LATER.

LOOKS UGLY BUT IT WORKS IN THE INIT AND UPDATE OF MODULE EDITOR A R_CAPSULE AND
A R_SPHERE ARE CREATED AND THEN TESTED INTERSECTION. THE POSITION OF BOTH GEOMETRY IS
THE SAME SO THE INTERSECTION WORKS. NEED TO TRY TO SEPARATE THEM (GIVEN THEM DIFFERENT
POSITIONS) TO TEST 0 FALSE WHEN THEY ARE NOT LOGICALLY TOUCHING.
*/

#endif


